# Generated by Django 4.0.4 on 2022-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_rename_name_patient_p_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='P_Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='P_NRIC',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='patient',
            name='P_Phone',
            field=models.IntegerField(),
        ),
    ]
