# Generated by Django 4.0.4 on 2022-08-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_patient_p_email_alter_patient_p_nric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='P_Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='P_NRIC',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='P_Phone',
            field=models.IntegerField(unique=True),
        ),
    ]
