# Generated by Django 4.0.4 on 2022-08-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_Password', models.CharField(max_length=30)),
                ('E_Name', models.CharField(max_length=30)),
                ('E_Phone', models.CharField(max_length=30)),
                ('E_Email', models.CharField(max_length=30)),
                ('E_RoleName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.role')),
            ],
        ),
    ]
