# Generated by Django 4.0.4 on 2022-08-18 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTime', models.DateTimeField()),
                ('D_Room', models.CharField(max_length=9)),
                ('D_SymptomRisk', models.CharField(max_length=50)),
                ('D_XRayRisk', models.CharField(max_length=50)),
                ('D_CovidDiagnosis', models.CharField(max_length=50)),
                ('D_Medication', models.TextField()),
                ('D_EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
                ('D_PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patient')),
            ],
        ),
    ]
