# Generated by Django 4.0.4 on 2022-08-21 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_diagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CR_DateTime', models.DateTimeField()),
                ('CR_Fever', models.BooleanField()),
                ('CR_DryCough', models.BooleanField()),
                ('CR_SoreThroat', models.BooleanField()),
                ('CR_BreathingDifficulty', models.BooleanField()),
                ('CR_OverseasTravel', models.BooleanField()),
                ('CR_CloseContact', models.BooleanField()),
                ('CR_PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.patient')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DQ_DateTime', models.DateTimeField()),
                ('DQ_SymptomRisk', models.CharField(max_length=30)),
                ('DQ_EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
                ('DQ_PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.casereport')),
            ],
        ),
        migrations.RenameField(
            model_name='diagnosis',
            old_name='DateTime',
            new_name='D_DateTime',
        ),
        migrations.CreateModel(
            name='XRayQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('XR_DateTime', models.DateTimeField()),
                ('XR_XRayRisk', models.CharField(max_length=30)),
                ('XR_EmployeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.employee')),
                ('XR_PatientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.doctorqueue')),
            ],
        ),
    ]
