# Generated by Django 4.0.4 on 2022-09-02 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_diagnosis_d_symptomrisk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='P_slug',
            field=models.SlugField(default='slug1', unique=True),
            preserve_default=False,
        ),
    ]
