# Generated by Django 4.0.4 on 2022-09-08 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_remove_xrayqueue_xr_employeeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='D_in_queue',
            field=models.BooleanField(default=True),
        ),
    ]
