# Generated by Django 4.0.4 on 2022-09-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_diagnosis_d_in_queue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='D_in_queue',
            new_name='D_dr_queue',
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='D_xr_queue',
            field=models.BooleanField(default=False),
        ),
    ]
