# Generated by Django 4.0.4 on 2022-09-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_rename_d_in_queue_diagnosis_d_dr_queue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='P_Email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='patient',
            name='P_NRIC',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='patient',
            name='P_Phone',
            field=models.IntegerField(),
        ),
    ]
