# Generated by Django 4.0.4 on 2022-09-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_patient_p_email_alter_patient_p_nric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='D_XRayPicture',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='D_CovidDiagnosis',
            field=models.CharField(choices=[('covid positive', 'Positive'), ('covid negative', 'Negative'), ('n/a', 'n/a')], default='positive', max_length=50),
        ),
    ]
