# Generated by Django 4.0.4 on 2022-10-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_diagnosis_d_xraypicture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='D_AtRiskOf',
            field=models.CharField(default='X-Ray not yet taken', max_length=100),
            preserve_default=False,
        ),
    ]
