# Generated by Django 4.1.3 on 2022-11-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0016_diagnosis_d_atriskof"),
    ]

    operations = [
        migrations.AddField(
            model_name="casereport",
            name="CR_FamilyWorksPublicExposedPlaces",
            field=models.BooleanField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casereport",
            name="CR_FeverTemp",
            field=models.CharField(
                choices=[
                    ("no fever", "<37.6°C"),
                    ("low fever", "37.6°C - 38.3°C"),
                    ("medium fever", "38.4°C - 39.0°C"),
                    ("high fever", "39.1°C - 39.9"),
                    ("emergency", ">40.0°C"),
                ],
                default="<37.6°C",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="casereport",
            name="CR_LargeGathering",
            field=models.BooleanField(default="1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="casereport",
            name="CR_PublicExposedPlaces",
            field=models.BooleanField(default="1"),
            preserve_default=False,
        ),
    ]
