# Generated by Django 4.1.3 on 2022-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0018_remove_casereport_cr_fever"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereport",
            name="CR_FeverTemp",
            field=models.CharField(max_length=50),
        ),
    ]
