# Generated by Django 4.1.3 on 2022-11-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0019_alter_casereport_cr_fevertemp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereport",
            name="CR_FeverTemp",
            field=models.CharField(
                choices=[
                    ("no fever", "<37.6°C"),
                    ("low fever", "37.6°C - 38.3°C"),
                    ("medium fever", "38.4°C - 39.0°C"),
                    ("high fever", "39.1°C - 39.9"),
                    ("emergency", ">40.0°C"),
                ],
                default="<37.6°C",
                max_length=50,
            ),
        ),
    ]
