# Generated by Django 4.1.3 on 2022-11-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0020_alter_casereport_cr_fevertemp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casereport",
            name="CR_FeverTemp",
            field=models.CharField(
                choices=[
                    ("<37.6°C", "<37.6°C"),
                    ("37.6°C - 38.3°C", "37.6°C - 38.3°C"),
                    ("38.4°C - 39.0°C", "38.4°C - 39.0°C"),
                    ("39.1°C - 39.9°C", "39.1°C - 39.9°C"),
                    (">40.0°C", ">40.0°C"),
                ],
                default="<37.6°C",
                max_length=50,
            ),
        ),
    ]
