# Generated by Django 4.1.3 on 2022-11-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0021_alter_casereport_cr_fevertemp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="D_CovidDiagnosis",
            field=models.CharField(
                choices=[
                    ("covid positive", "Positive"),
                    ("covid negative", "Negative"),
                    ("n/a", "n/a"),
                ],
                default="positive",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="D_SymptomRisk",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="diagnosis",
            name="D_XRayRisk",
            field=models.CharField(max_length=100),
        ),
    ]
