# Generated by Django 4.1.3 on 2022-11-08 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0022_alter_diagnosis_d_coviddiagnosis_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="P_slug",
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
