# Generated by Django 4.1.3 on 2022-11-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0023_alter_patient_p_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosis",
            name="D_XRayPicture",
            field=models.ImageField(max_length=110, upload_to="images"),
        ),
    ]
