# Generated by Django 4.1.3 on 2022-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0024_alter_diagnosis_d_xraypicture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="P_slug",
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
