# Generated by Django 4.1.3 on 2022-11-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0025_alter_patient_p_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="E_Email",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="E_Name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="E_Password",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="employee",
            name="E_Phone",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="role",
            name="R_RoleName",
            field=models.CharField(max_length=255),
        ),
    ]
